In [22]:
import torch


In [32]:
tmp = torch.tensor([[[1,2],[3,4]],
              [[5,6],[7,8]],
              [[9,10],[11,12]]])

In [33]:
tmp

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [34]:
tmp_mask = torch.tensor([[True,False],
              [False,True],
              [False,False]])

In [35]:
mask_val = torch.tensor([0,]*tmp.shape[-1])

In [36]:
mask_val

tensor([0, 0])

In [37]:
tmp_mask

tensor([[ True, False],
        [False,  True],
        [False, False]])

In [38]:
tmp[tmp_mask] = mask_val

In [39]:
tmp

tensor([[[ 0,  0],
         [ 3,  4]],

        [[ 5,  6],
         [ 0,  0]],

        [[ 9, 10],
         [11, 12]]])

In [17]:
t = ()
t1 = (1,)
t2 = (2,)

In [19]:
t += t1

In [20]:
t

(1, 1)

In [21]:
t += t2

In [22]:
t


(1, 1, 2)